# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qrun5oWh6SVzgZkMHyyEz7z7MXy4VPXG

**TITIANIC SURVIVOR ANALYSIS**


---

K S SAIVAIBHAV
SHAPE AI PROJECT

**Importing libraries**
"""

import numpy as np
import pandas as pd

"""**Loading the dataset and exploring it**"""

df = pd.read_csv('train.csv')
df.head()

df.shape

"""**Handling Null Values**

Finding all the null values in the dataset
"""

df.isnull().sum()

"""Seeing whose null value contribution out of all the columns is greater than 35%"""

drop_col = df.isnull().sum()[df.isnull().sum() > (35/100 * df.shape[0])]
drop_col

drop_col.index

"""Dropping the column CABIN"""

df.drop(drop_col.index, axis=1, inplace=True)
df.isnull().sum()

"""
Is there any null values left in the dataset"""

df.fillna(df.mean(), inplace = True)
df.isnull().sum()

"""
As Embarked col has strings, we would replace NA values with the most frequent occuring string"""

df['Embarked'].describe()

df.fillna('S', inplace = True)
df.isnull().sum()

"""**Finding correlation and drawing conclusions**

Getting the Correlation table, helps to understand how the two col's have relation between them
"""

df.corr()

"""
Combining Parch and SibSp as their corr value is high, then dropping both the cols from the dataset"""

df['FamilySize'] = df['Parch'] + df['SibSp']
df.drop(['Parch','SibSp'], axis=1, inplace=True)
df.corr()

"""
Marking 1 if the person travelled alone, else 0 (ie, travelled with any other person)"""

df['Alone'] = [0 if df['FamilySize'][i]>0 else 1 for i in df.index]
df.head()

"""
Checking the probability(by cal mean) of the person's survival rate with the factor that he/she is travelling alone or not"""

df.groupby(['Alone'])['Survived'].mean()

"""
Clearly if travelling with family there are chances of your survival

Now, checking the correlation between alone and fare"""

df[['Alone','Fare']].corr()

"""Clearly if you are with the family the charges/fare would be higher( as the value is high and the negative sign indicates of being not alone)

Checking if the gender affects the rate of your survival
"""

df['Sex'] = [0 if df['Sex'][i]=='male' else 1 for i in df.index]
df.groupby(['Sex'])['Survived'].mean()

"""
Cleary the probability(by cal mean) of the person's survival rate depends on their gender, if female chances are high that you'll survive

Trying to find out people boarded from which station survived the most"""

df.groupby(['Embarked'])['Survived'].mean()

"""**Conclusion**<br/>
Chances of your survival is high, if:

you are not traelling alone
you are female
you have boarded from cherborg(C)
"""